# Generated by Django 2.0.4 on 2018-04-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120, verbose_name='Услуга')),
                ('price', models.CharField(max_length=60, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название области')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Поставщик')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес центрального офиса')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ServiceArea')),
            ],
        ),
    ]
