# Generated by Django 2.0.4 on 2018-05-03 18:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import supply.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=60, validators=[supply.validators.validate_service_price], verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название области')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Сервисная зона',
                'verbose_name_plural': 'Сервисные зоны',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=30, validators=[supply.validators.validate_phonenumber], verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес центрального офиса')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AddField(
            model_name='servicearea',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='supply.Supplier'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='supply.ServiceArea'),
        ),
    ]
