# Generated by Django 2.0.4 on 2018-04-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.Service'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='service_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.ServiceArea'),
        ),
    ]
