# Generated by Django 2.0.4 on 2018-05-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='supply.ServiceArea'),
        ),
    ]
