# Generated by Django 2.0.4 on 2018-04-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_auto_20180421_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='service',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='service_area',
        ),
        migrations.AddField(
            model_name='service',
            name='service_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.ServiceArea'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.Supplier'),
        ),
    ]
