# Generated by Django 2.0.4 on 2018-04-22 17:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20180421_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Область'),
        ),
    ]
