# Generated by Django 2.0.4 on 2018-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20180507_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название услуги'),
        ),
    ]
