# Generated by Django 2.0.4 on 2018-04-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_auto_20180423_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='supply.Supplier'),
        ),
    ]
