# Generated by Django 2.0.4 on 2018-04-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_auto_20180424_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='supply.ServiceArea'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название области'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
    ]
