# Generated by Django 2.0.4 on 2018-05-01 13:17

from django.db import migrations, models
import supply.validators


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_auto_20180424_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[supply.validators.validate_phonenumber], verbose_name='Номер телефона'),
        ),
    ]
